"""authors_books

Revision ID: 4ef956430478
Revises: 
Create Date: 2023-04-05 14:46:16.276723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4ef956430478"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("surname", sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("authors", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_authors_name"), ["name"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_authors_surname"), ["surname"], unique=False
        )

    op.create_table(
        "books",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=128), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("publisher", sa.String(length=128), nullable=True),
        sa.Column("genre", sa.String(length=128), nullable=True),
        sa.Column("done", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("books", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_books_done"), ["done"], unique=False)
        batch_op.create_index(batch_op.f("ix_books_genre"), ["genre"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_books_publisher"), ["publisher"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_books_title"), ["title"], unique=True)
        batch_op.create_index(batch_op.f("ix_books_year"), ["year"], unique=False)

    op.create_table(
        "authors_books",
        sa.Column("author_id", sa.Integer(), nullable=True),
        sa.Column("book_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["authors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("authors_books")
    with op.batch_alter_table("books", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_books_year"))
        batch_op.drop_index(batch_op.f("ix_books_title"))
        batch_op.drop_index(batch_op.f("ix_books_publisher"))
        batch_op.drop_index(batch_op.f("ix_books_genre"))
        batch_op.drop_index(batch_op.f("ix_books_done"))

    op.drop_table("books")
    with op.batch_alter_table("authors", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_authors_surname"))
        batch_op.drop_index(batch_op.f("ix_authors_name"))

    op.drop_table("authors")
    # ### end Alembic commands ###
