"""hire table

Revision ID: 663bdfe2a55b
Revises: 4ef956430478
Create Date: 2023-04-05 16:35:03.443596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '663bdfe2a55b'
down_revision = '4ef956430478'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start', sa.String(length=128), nullable=True),
    sa.Column('end', sa.String(length=128), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hires', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hires_end'), ['end'], unique=False)
        batch_op.create_index(batch_op.f('ix_hires_start'), ['start'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hires', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hires_start'))
        batch_op.drop_index(batch_op.f('ix_hires_end'))

    op.drop_table('hires')
    # ### end Alembic commands ###
