"""unique authors

Revision ID: efadf1c1758a
Revises: 663bdfe2a55b
Create Date: 2023-04-05 20:29:14.861088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efadf1c1758a'
down_revision = '663bdfe2a55b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_index('ix_authors_name_new')
        batch_op.create_index(batch_op.f('ix_authors_name'), ['name'], unique=True)
        batch_op.drop_column('surname')
        batch_op.drop_column('name_new')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_new', sa.VARCHAR(length=256), nullable=True))
        batch_op.add_column(sa.Column('surname', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_index(batch_op.f('ix_authors_name'))
        batch_op.create_index('ix_authors_name_new', ['name_new'], unique=False)

    # ### end Alembic commands ###
